[project]
name = "aws-lambda-pytest"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.42.31",
    "boto3-stubs==1.42.31",
    "moto>=5.1.20",
    "pytest>=9.0.2",
    "pytest-mock>=3.15.1",
]
